---
functional:
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность фильтровать товары
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - При покупке товаров у сайта должна быть возможность ввести номер карты для списания денег
  - Товары должны быть рассортированы по категориям/ценам/фирмам для удобства пользователя
  - В каждой карточке товара должен быть полный перечень характеристик и фотографии хорошего качества
  - Сайт должен работать через HTTPS для шифрования данных и безопасности соединения
